services:
  app:
    image: wiwit
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - APP_KEY=base64:A51OB+SLeNBateUyIcBQGtXMTEja/ks7ct9zg3liTzY= # regenerate this key for production use
      - DB_HOST=db
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wiwit
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  pma:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - '9001:80'
    depends_on:
      - db

volumes:
  db_data:
