name: Automatic Deployments

on:
  workflow_dispatch:

concurrency: deploy-targets

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # This is required for the Tailscale action to request a JWT from GitHub

    steps:
      - name: Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          audience: ${{ secrets.TS_AUDIENCE }}
          tags: tag:ci

      - name: Ping targets
        run: tailscale ping tomyam.eel-arowana.ts.net

      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.TARGET_HOST}}
          username: ${{ vars.TARGET_USERNAME}}
          password: dummy # https://github.com/appleboy/ssh-action/issues/344#issuecomment-2906895821
          script: |
            set -e
            cd /opt/stacks/wiwit
            docker compose pull
            docker compose up -d

      - name: Write success
        run: echo 'App deployed 🚀' >> $GITHUB_STEP_SUMMARY
